### ISSUE TITLE
Set up mission_core to take in parameters other than comma seperated string

### ISSUE THREAD

**Issue by fnivek** [uf-mil-archive/software-common#7]
It would be useful for the [mission_core run_missions script](https://github.com/uf-mil/software-common/blob/master/mission_core/scripts/run_missions) to take in parameters in a way that allows us to easily pass numbers strings and anything else if we need it.

**Comment by forrestv** [comment]
Working on this.

**Comment by forrestv** [comment]
Closed.

**Comment by fnivek** [comment]
Thanks Forrest!
